# Part of this file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import *

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


# region MainWindow
window = Tk()
window.title("GrubHub")
window.geometry("375x812")
window.configure(bg="#23232E")

canvas = Canvas(
    window,
    bg="#23232E",
    height=812,
    width=375,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
# endregion

global quantity, totalDouble, total, price
quantity = 0
totalDouble = 0.0
total = "{:.2f}".format(totalDouble)
price = 3

button_image_5 = PhotoImage(file=relative_to_assets("button_5.png"))
button_image_4 = PhotoImage(file=relative_to_assets("button_4.png"))


def quantity_change(change, quantity_text, priceText, deal=False, dealPrice=3):
    global quantity, totalDouble, total, price

    if deal:
        price = dealPrice
        totalDouble = quantity * price
    else:
        quantity += change
        totalDouble += change * price

    total = "{:.2f}".format(totalDouble)
    print(total)

    if quantity < 0:
        quantity = 0
        totalDouble = 0

    if quantity > 0:
        button_4.configure(image=button_image_5)
        priceText.place(x=209.0,
                        y=765.5,
                        width=40.0,
                        height=15.0)
    else:
        priceText.place_forget()
        button_4.configure(image=button_image_4)
        totalDouble = 0

    canvas.itemconfigure(quantity_text, text=quantity)
    priceText.configure(text=total)
    window.update_idletasks()
    window.update()


# region text items

canvas.create_text(
    12.0,
    456.0,
    anchor="nw",
    text="Current Deals",
    fill="#FFFFFF",
    font=("Roboto", 18 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    184.0,
    392.0,
    image=image_image_1
)

canvas.create_text(
    64.0,
    10.0,
    anchor="nw",
    text="Menu Item",
    fill="#FFFFFF",
    font=("Roboto Bold", 20 * -1)
)

canvas.create_text(
    12.0,
    302.0,
    anchor="nw",
    text="Meat Sub",
    fill="#FFFFFF",
    font=("Roboto", 18 * -1)
)

canvas.create_text(
    12.0,
    332.0,
    anchor="nw",
    text="Meat sub with just random condiments",
    fill="#AFAFBA",
    font=("Roboto", 14 * -1)
)

canvas.create_text(
    311.0,
    303.0,
    anchor="nw",
    text="$3.00",
    fill="#FFFFFF",
    font=("Roboto", 18 * -1)
)

canvas.create_text(
    12.0,
    371.0,
    anchor="nw",
    text="Quantity",
    fill="#FFFFFF",
    font=("Roboto", 18 * -1)
)

quantity_text = canvas.create_text(
    62.0,
    414.0,
    anchor="center",
    text=quantity,
    fill="#FFFFFF",
    font=("Roboto", 18 * -1)
)

priceText = Label(
    window,
    text=total,
    font=("Roboto bold", 15 * -1),
    bg="#3F9D4E"
)
priceText.place(
    x=209.0,
    y=765.5,
    width=40.0,
    height=15.0
)
priceText.place_forget()

# endregion

# region buttons
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: exit(),
    relief="flat"
)
button_1.place(
    x=14.0,
    y=6.0,
    width=34.0,
    height=34.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: quantity_change(1, quantity_text, priceText),
    relief="flat"
)
button_2.place(
    x=83.0,
    y=403.0,
    width=21.0,
    height=25.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: quantity_change(-1, quantity_text, priceText),
    relief="flat"
)
button_3.place(
    x=19.0,
    y=403.0,
    width=25.0,
    height=25.0
)

initImage = PhotoImage(file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=initImage,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=25.0,
    y=753.0,
    width=324.0,
    height=40.0
)

priceText.lift()

# endregion

# region deals scrollables

# new frame
dealsFrame = Frame(window, height=212, width=343)  # 23232E
dealsFrame.place(x=15, y=498)

# create NEW canvas
deals_canvas = Canvas(dealsFrame, height=212, width=343)  # 23232E
deals_canvas.pack(side=LEFT, fill=BOTH, expand=1)  # place(x=15, y=498)

# create scrollbar to new canvas
dealsScrollbar = Scrollbar(dealsFrame, orient="horizontal", command=deals_canvas.xview)
dealsScrollbar.place(x=0, y=195, width=343)

# config new canvas
deals_canvas.configure(xscrollcommand=dealsScrollbar.set)
deals_canvas.bind('<Configure>', lambda e: deals_canvas.config(scrollregion=deals_canvas.bbox("all")))

# create ANOTHER frame inside of canvas
secondDealsFrame = Frame(deals_canvas, height=210, width=341, bg="#23232E")

# add that new frame to the canvas
deals_canvas.create_window((0, 0), window=secondDealsFrame, anchor="nw")

'''for thing in range(100):
    Button(secondDealsFrame, text="Button " + str(thing)).grid(row=0, column=thing, pady=5, padx=10)'''
# endregion

# region deal1
deals1Canvas = Canvas(
    secondDealsFrame,
    bg="#23232E",
    height=212,
    width=343,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

deals1Canvas.grid(row=0, column=0, pady=5, padx=10)

deals1Canvas.create_text(
    11.0,
    15.0,
    anchor="nw",
    text="Meat Sub Combo Meal ",
    fill="#FFFBFB",
    font=("Roboto", 18 * -1)
)

deals1Canvas.create_text(
    11.0,
    42.0,
    anchor="nw",
    text="1x Meat Sub",
    fill="#FFFFFF",
    font=("Roboto", 13 * -1)
)

deals1Canvas.create_text(
    11.0,
    62.0,
    anchor="nw",
    text="1x Large Fry",
    fill="#FFFFFF",
    font=("Roboto", 13 * -1)
)

deals1Canvas.create_text(
    272.0,
    15.0,
    anchor="nw",
    text="$7.00",
    fill="#FFFFFF",
    font=("Roboto", 18 * -1)
)

deals1Canvas.create_text(
    11.0,
    82.0,
    anchor="nw",
    text="1x Large Drink",
    fill="#FFFFFF",
    font=("Roboto", 13 * -1)
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    deals1Canvas,
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: quantity_change(1, quantity_text, priceText, deal=True, dealPrice=7),
    relief="flat"
)
button_6.place(
    x=10.0,
    y=143.0,
    width=324.0,
    height=40.0
)
# endregion

# region deal2
deals2Canvas = Canvas(
    secondDealsFrame,
    bg="#23232E",
    height=212,
    width=343,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

deals2Canvas.grid(row=0, column=1, pady=5, padx=10)

deals2Canvas.create_text(
    11.0,
    15.0,
    anchor="nw",
    text="Meat Sub Combo Meal ",
    fill="#FFFBFB",
    font=("Roboto", 18 * -1)
)

deals2Canvas.create_text(
    11.0,
    42.0,
    anchor="nw",
    text="1x Meat Sub",
    fill="#FFFFFF",
    font=("Roboto", 13 * -1)
)

deals2Canvas.create_text(
    11.0,
    62.0,
    anchor="nw",
    text="1x Large Shake",
    fill="#FFFFFF",
    font=("Roboto", 13 * -1)
)

deals2Canvas.create_text(
    272.0,
    15.0,
    anchor="nw",
    text="$4.00",
    fill="#FFFFFF",
    font=("Roboto", 18 * -1)
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_7 = Button(
    deals2Canvas,
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: quantity_change(1, quantity_text, priceText, deal=True, dealPrice=4),
    relief="flat"
)
button_7.place(
    x=10.0,
    y=143.0,
    width=324.0,
    height=40.0
)
# endregion

# region deal3
deals3Canvas = Canvas(
    secondDealsFrame,
    bg="#23232E",
    height=212,
    width=343,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

deals3Canvas.grid(row=0, column=2, pady=5, padx=10)

deals3Canvas.create_text(
    11.0,
    15.0,
    anchor="nw",
    text="Meat Sub Combo Meal ",
    fill="#FFFBFB",
    font=("Roboto", 18 * -1)
)

deals3Canvas.create_text(
    11.0,
    42.0,
    anchor="nw",
    text="1x Meat Sub",
    fill="#FFFFFF",
    font=("Roboto", 13 * -1)
)

deals3Canvas.create_text(
    11.0,
    62.0,
    anchor="nw",
    text="1x Apple Pie",
    fill="#FFFFFF",
    font=("Roboto", 13 * -1)
)

deals3Canvas.create_text(
    272.0,
    15.0,
    anchor="nw",
    text="$5.00",
    fill="#FFFFFF",
    font=("Roboto", 18 * -1)
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_8 = Button(
    deals3Canvas,
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: quantity_change(1, quantity_text, priceText, deal=True, dealPrice=5),
    relief="flat"
)
button_8.place(
    x=10.0,
    y=143.0,
    width=324.0,
    height=40.0
)
# endregion


window.resizable(False, False)
window.mainloop()
